name: w_module_example
version: 2.1.2
description: Base module classes with a well defined lifecycle for modular Dart applications.
homepage: https://github.com/Workiva/w_module
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.2
  build_web_compilers: '>=3.0.0 <5.0.0'
  dependency_validator: ^3.2.2
  meta: ^1.16.0
  opentracing: ^1.0.1
  over_react: ^5.0.0
  platform_detect: '>=1.4.2 <3.0.0'
  react: ^7.0.0
  w_common: ^3.0.0
  w_flux: ^3.0.0
  w_module:

dependency_overrides:
  w_module:
    path: ../
  react:
    git:
      url: git@github.com:Workiva/react-dart.git
      ref: react-18-2-0-testing
