name: w_module_example
version: 2.1.2
description: Base module classes with a well defined lifecycle for modular Dart applications.
homepage: https://github.com/Workiva/w_module
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.2
  build_web_compilers: ^3.0.0
  dependency_validator: ^3.2.2
  meta: ^1.6.0
  opentracing: ^1.0.1
  over_react: ^4.4.0
  platform_detect: '>=1.4.2 <3.0.0'
  react: ^6.1.6
  w_common: '>=2.0.0 <4.0.0'
  w_flux: ^2.10.21
  w_module:

dependency_validator:
  ignore:
    - mockito

dependency_overrides:
  w_module: ^3.0.0
  w_transport: 
    git:
      url: git@github.com:Workiva/w_transport.git
      ref: tweak_collection_dep
