version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      gha:
        patterns: ["*"]
  - package-ecosystem: pub
    versioning-strategy: increase
    directories:
      - /
      - /example
    schedule:
      interval: weekly
    cooldown:
      default-days: 4