language: dart

sudo: required
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.pub-cache
jobs:
  include:
    - dart: 2.7.2
      name: "SDK: 2.7.2"
      script:
        - pub run dart_dev analyze
        - pub run dart_dev test --release
    - dart: stable
      name: "SDK: stable"
      script:
        - pub run dart_dev format --check
        - pub run dart_dev analyze
        - pub run dart_dev test
        - pub run dart_dev test --release
    - dart: dev
      name: "SDK: dev"
      script:
        - pub run dart_dev analyze
        - pub run dart_dev test --release
