language: dart
dart:
  - 2.4.1
  - stable
  - dev
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.pub-cache
script:
  - pub get
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dart_dev test
