/// Decorate the library with the `DeferredModule` annotation,
/// pointing it to the necessary module classes.
@DeferredModule(
    #example_module.ExampleModule,
    #example_module.ExampleApi,
    #example_module.ExampleComponents,
    #example_module.ExampleEvents)
library w_module.example.deferred.deferred_example_module;

/// Import anything that would be needed for an abstract view
/// of the module. In other words, you should only have to import
/// the bare minimum in order to accurately type the module and
/// its sub classes (API, Events, Components).
import 'dart:async';
import 'package:w_module/w_module.dart' show DeferredModule, Module;
import './example_module.dart' deferred as example_module;

/// Include the deferred module code generated by the deferred
/// module generator.
part './deferred_example_module.g.dart';