name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.13.4, stable, beta, dev ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v0.2
        with:
          sdk: ${{ matrix.sdk }}

      - id: install
        name: Install dependencies
        working-directory: ./w_module
        run: dart pub get

      - name: Validate dependencies
        working-directory: ./w_module
        run: dart run dependency_validator
        if: always() && steps.install.outcome == 'success'

      - name: Analyze project source
        working-directory: ./w_module
        run: dart analyze
        if: always() && steps.install.outcome == 'success'

      - name: Run tests
        working-directory: ./w_module
        run: dart test
        if: always() && steps.install.outcome == 'success'

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v0.2
        with:
          sdk: 2.13.4

      - id: install
        name: Install dependencies
        working-directory: ./w_module
        run: dart pub get

      - name: Verify formatting
        working-directory: ./w_module
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'